---
  elasticsearch_major_version: 7.x
  elasticsearch_cluster_name: my_cluster
  elasticsearch_node_name: my_node
  elasticsearch_network_host: visualserver
  elasticsearch_http_port: 9200 
  kibana_major_version: 7.x
  kibana_server_host: 0.0.0.0
  kibana_server_port: 5601
  kibana_elasticsearch_url: "http://localhost:9200"